ci: Retry on timeout
Signed-off-by: oliver könig <okoenig@nvidia.com>

diff --git a/.github/workflows/_test_template.yml b/.github/workflows/_test_template.yml
--- a/.github/workflows/_test_template.yml
+++ b/.github/workflows/_test_template.yml
@@ -82,35 +82,57 @@ jobs:
 
         - id: main
           name: Run main script
-          timeout-minutes: ${{ inputs.TIMEOUT }}
-          run: |
-            mkdir -p ${{ github.run_id }}
-            cd ${{ github.run_id }}/
-            rm .coverage || true
-            set +e 
-            (  
-              set -e
+          uses: nick-fields/retry@v3
+          with:
+            timeout_seconds: ${{ inputs.TIMEOUT }}
+            max_attempts: 3
+            retry_on: timeout
+            command: |
+              mkdir -p ${{ github.run_id }}
+              cd ${{ github.run_id }}/
+              rm .coverage || true
+              set +e 
+              (  
+                set -e
 
-              docker exec nemo_container_${{ github.run_id }} bash -c '${{ inputs.SCRIPT }}'
-            ) 2> >(tee err.log)
+                docker exec nemo_container_${{ github.run_id }} bash -c '${{ inputs.SCRIPT }}'
+              ) 2> >(tee err.log)
 
-            EXIT_CODE=$?
+              EXIT_CODE=$?
 
-            set -x
+              set -x
 
-            log=$(tail -c 2000 err.log |  base64 -w 0)
-            echo "log=$log" >> "$GITHUB_OUTPUT"
-            
-            potential_infra_failure=$(cat err.log | grep -Eqiw "device" && echo true || echo false)
-            echo "potential_infra_failure=$potential_infra_failure" >> "$GITHUB_OUTPUT"
+              log=$(tail -c 2000 err.log |  base64 -w 0)
+              echo "log=$log" >> "$GITHUB_OUTPUT"
+              
+              potential_infra_failure=$(cat err.log | grep -Eqiw "device" && echo true || echo false)
+              echo "potential_infra_failure=$potential_infra_failure" >> "$GITHUB_OUTPUT"
 
-            coverage_report=coverage-${{ github.run_id }}-$(uuidgen)
-            echo "coverage_report=$coverage_report" >> "$GITHUB_OUTPUT"
+              coverage_report=coverage-${{ github.run_id }}-$(uuidgen)
+              echo "coverage_report=$coverage_report" >> "$GITHUB_OUTPUT"
 
-            docker exec nemo_container_${{ github.run_id }} bash -c 'ls -al'
-            docker cp nemo_container_${{ github.run_id }}:/workspace/.coverage .coverage 
+              docker exec nemo_container_${{ github.run_id }} bash -c 'ls -al'
+              docker cp nemo_container_${{ github.run_id }}:/workspace/.coverage .coverage 
 
-            exit $EXIT_CODE
+              exit $EXIT_CODE
+            on_retry_command: |
+              docker container stop nemo_container_${{ github.run_id }} || true
+              docker container rm nemo_container_${{ github.run_id }} || true
+              ARG=("")
+              if [[ "${{ inputs.RUNNER }}" != *cpu* ]]; then
+                ARG=("--runtime=nvidia --gpus all")
+              fi
+
+              docker run \
+                --rm \
+                -d \
+                --name nemo_container_${{ github.run_id }} ${ARG[@]} \
+                --shm-size=64g \
+                --env TRANSFORMERS_OFFLINE=0 \
+                --env HYDRA_FULL_ERROR=1 \
+                --env HF_HOME=/home/TestData/HF_HOME \
+                --volume /mnt/datadrive/TestData:/home/TestData nemoci.azurecr.io/nemo_container:${{ github.run_id }} \
+                bash -c "sleep $(( ${{ inputs.TIMEOUT }} * 60 + 60 ))"
         
         - name: Upload artifacts
           uses: actions/upload-artifact@v4
