test
Signed-off-by: oliver könig <okoenig@nvidia.com>

diff --git a/.github/workflows/_test_template.yml b/.github/workflows/_test_template.yml
--- a/.github/workflows/_test_template.yml
+++ b/.github/workflows/_test_template.yml
@@ -122,24 +122,24 @@ jobs:
             shell: bash
             retry_on: timeout
             command: /bin/bash ${{ github.run_id }}/job.sh 
-            on_retry_command: |
-              docker container stop nemo_container_${{ github.run_id }} || true
-              docker container rm nemo_container_${{ github.run_id }} || true
-              ARG=("")
-              if [[ "${{ inputs.RUNNER }}" != *cpu* ]]; then
-                ARG=("--runtime=nvidia --gpus all")
-              fi
+            # on_retry_command: |
+            #   docker container stop nemo_container_${{ github.run_id }} || true
+            #   docker container rm nemo_container_${{ github.run_id }} || true
+            #   ARG=("")
+            #   if [[ "${{ inputs.RUNNER }}" != *cpu* ]]; then
+            #     ARG=("--runtime=nvidia --gpus all")
+            #   fi
 
-              docker run \
-                --rm \
-                -d \
-                --name nemo_container_${{ github.run_id }} ${ARG[@]} \
-                --shm-size=64g \
-                --env TRANSFORMERS_OFFLINE=0 \
-                --env HYDRA_FULL_ERROR=1 \
-                --env HF_HOME=/home/TestData/HF_HOME \
-                --volume /mnt/datadrive/TestData:/home/TestData nemoci.azurecr.io/nemo_container:${{ github.run_id }} \
-                bash -c "sleep $(( ${{ inputs.TIMEOUT }} * 60 + 60 ))"
+            #   docker run \
+            #     --rm \
+            #     -d \
+            #     --name nemo_container_${{ github.run_id }} ${ARG[@]} \
+            #     --shm-size=64g \
+            #     --env TRANSFORMERS_OFFLINE=0 \
+            #     --env HYDRA_FULL_ERROR=1 \
+            #     --env HF_HOME=/home/TestData/HF_HOME \
+            #     --volume /mnt/datadrive/TestData:/home/TestData nemoci.azurecr.io/nemo_container:${{ github.run_id }} \
+            #     bash -c "sleep $(( ${{ inputs.TIMEOUT }} * 60 + 60 ))"
         
         - name: Upload artifacts
           uses: actions/upload-artifact@v4
